use serde_json::Value;

pub fn get_f64(v: &Value) -> Option<f64> {
    v.as_f64()
        .or_else(|| v.as_str().and_then(|s| s.parse::<f64>().ok()))
}

pub fn get_i64(v: &Value) -> Option<i64> {
    v.as_i64().or_else(|| get_f64(v).map(|f| f.round() as i64))
}

pub fn visible_width(s: &str) -> usize {
    let mut count = 0;
    let mut in_csi = false;
    let mut in_osc = false;
    let mut chars = s.chars().peekable();

    while let Some(c) = chars.next() {
        if c == '\x1b' {
            if let Some(&next) = chars.peek() {
                if next == '[' {
                    chars.next();
                    in_csi = true;
                    continue;
                } else if next == ']' {
                    chars.next();
                    in_osc = true;
                    continue;
                }
            }
        }
        if in_csi {
            if c.is_ascii_alphabetic() {
                in_csi = false;
            }
            continue;
        }
        if in_osc {
            if c == '\x07' {
                in_osc = false;
            } else if c == '\x1b' {
                if let Some(&'\\') = chars.peek() {
                    chars.next();
                    in_osc = false;
                }
            }
            continue;
        }
        count += 1;
    }
    count
}

pub fn get_terminal_width(json: &Value) -> usize {
    if let Some(w) = json["terminal_width"].as_u64() {
        if w > 0 {
            return w as usize;
        }
    }
    if let Some(w) = json["columns"].as_u64() {
        if w > 0 {
            return w as usize;
        }
    }
    if let Some((terminal_size::Width(w), _)) = terminal_size::terminal_size() {
        if w > 0 {
            return w as usize;
        }
    }
    if let Ok(cols) = std::env::var("COLUMNS") {
        if let Ok(w) = cols.parse::<usize>() {
            if w > 0 {
                return w;
            }
        }
    }
    80
}

pub fn attach_bottom_right_tag(last_line: &mut String, term_width: usize) {
    let tag = format!(
        "\n{}-- generated by agent-statusline v{}{}",
        crate::colors::DIM,
        env!("CARGO_PKG_VERSION"),
        crate::colors::RESET
    );
    let tag_raw_len = tag.chars().count();
    let current_width = visible_width(last_line);

    if current_width + tag_raw_len + 2 <= term_width {
        let pad = term_width - current_width - tag_raw_len;
        last_line.push_str(&" ".repeat(pad));
        last_line.push_str(&tag);
    } else {
        last_line.push_str("  ");
        last_line.push_str(&tag);
    }
}
